post http://localhost:3002/signup
Content-Type: application/json

{
  "username": "b",
  "password": "b"
}

###
post http://localhost:3002/signin
Content-Type: application/json

{
  "username":"b",
  "password":"b"
}

###
get http://localhost:3002/protected

###
get http://localhost:3002/signout

###
get http://localhost:3002/todos

###
post http://localhost:3002/todos
Content-Type: application/json

{
  "title": "second todo!",
  "desc": "testing",
  "prio": "low",
  "due": "1670440199113",
  "done": false,
  "projectId": 3
}