
// sign up
post http://localhost:3002/auth/signup
Content-Type: application/json

{
  "username": "d",
  "password": "d"
}

###

// sign in
post http://localhost:3002/auth/signin
Content-Type: application/json

{
  "username":"c",
  "password":"c"
}

###

// check protected
get http://localhost:3002/protected


###
get http://localhost:3002/auth/signout

###

// create project
post http://localhost:3002/projects
Content-Type: application/json

{
  "title":"second project!"
}

