post http://localhost:3002/signup
Content-Type: application/json

{
  "username": "b",
  "password": "b"
}

###
post http://localhost:3002/signin
Content-Type: application/json

{
  "username":"b",
  "password":"b"
}

###
get http://localhost:3002/protected

###
get http://localhost:3002/signout

###
get http://localhost:3002/todos

###
post http://localhost:3002/todos
Content-Type: application/json

{
  "title": "third todo!",
  "desc": "lol",
  "prio": "low",
  "done": false
}

###
put http://localhost:3002/todos/update/5
Content-Type: application/json

{
  "title": "second todo!",
  "desc": "lol",
  "prio": "high",
  "done": true
}

###
delete http://localhost:3002/todos/delete/2